name: Trigger Ayuna for stay wake up

on:
  schedule:
    - cron: "3 * * * *"
jobs:
  build:
    name: Trigger ayuna
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: echo
        run: echo Triggering
      - name: Run ping
        uses: Satak/webrequest-action@v1.2.3
        with:
          url: "https://ayuna-sticker.herokuapp.com/ping"
          method: GET